# Generated by Django 3.1.5 on 2021-01-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Junior', max_length=10, verbose_name='position name'),
        ),
    ]
